# kubectl apply --filename ../cert-manager.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: opentdf
spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    cert: opentdf-us-tls
  name: opentdf-us-tls
  namespace: istio-ingress
spec:
  dnsNames:
    - opentdf.us
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-cluster-issuer
  privateKey:
    rotationPolicy: Always
  renewBefore: 720h0m0s
  secretName: opentdf-us-tls
