apiVersion: v1
kind: Secret
metadata:
  name: attributes-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.attributes.postgres.password }}

---

apiVersion: v1
kind: Secret
metadata:
  name: entitlement-pdp-secret
type: Opaque
data:
  opaPolicyPullSecret: {{ .Values.entitlementpdp.opaPolicyPullSecret | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: entitlement-store-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.entitlementstore.postgres.password }}
  EAS_PRIVATE_KEY: |-
        {{ .Files.Get "keystore/mock-claims-private-key.pem" | b64enc }}
  EAS_CERTIFICATE: |-
        {{ .Files.Get "keystore/mock-claims-certificate.pem" | b64enc }}
  KAS_EC_SECP256R1_CERTIFICATE: |-
        {{ .Files.Get "keystore/mock-key-access-ec-certificate.pem" | b64enc }}
  KAS_CERTIFICATE: |-
        {{ .Files.Get "keystore/mock-key-access-certificate.pem" | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: entitlements-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.entitlements.postgres.password }}

---

apiVersion: v1
kind: Secret
metadata:
  name: kas-secrets
type: Opaque
data:
  EAS_CERTIFICATE: |-
        {{ .Files.Get "keystore/mock-claims-certificate.pem" | b64enc }}
  KAS_EC_SECP256R1_CERTIFICATE: |-
        {{ .Files.Get "keystore/mock-key-access-ec-certificate.pem" | b64enc }}
  KAS_CERTIFICATE: |-
        {{ .Files.Get "keystore/mock-key-access-certificate.pem" | b64enc }}
  KAS_EC_SECP256R1_PRIVATE_KEY: |-
        {{ .Files.Get "keystore/mock-key-access-ec-private-key.pem" | b64enc }}
  KAS_PRIVATE_KEY: |-
        {{ .Files.Get "keystore/mock-key-access-private-key.pem" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-bootstrap-secret
type: Opaque
stringData:
  CLIENT_SECRET: "123-456"
  keycloak_admin_username: keycloakadmin
  keycloak_admin_password: mykeycloakpassword
  ATTRIBUTES_USERNAME: user1
  ATTRIBUTES_PASSWORD: testuser123
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
type: Opaque
data:
  KEYCLOAK_ADMIN: {{ "keycloakadmin" | b64enc | quote  }}
  KEYCLOAK_ADMIN_PASSWORD: {{ "mykeycloakpassword" | b64enc | quote }}
  KC_DB_USERNAME: {{ "postgres" | b64enc | quote }}
  KC_DB_PASSWORD: {{ "myPostgresPassword" | b64enc | quote }}
  KC_DB_URL_HOST: {{ "postgresql" | b64enc | quote }}
  KC_DB_URL_DATABASE: {{ "keycloak_database" | b64enc | quote }}
