const TDFDATA = [
              [ // A
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
              ],
              [ // B
               "ocean", 
               "ocean", 
               "ship1", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
              ],
              [ // C
               "ocean", 
               "ocean", 
               "ship1", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
              ],
              [ // D
               "ship1", 
               "ocean", 
               "ship1", 
               "ocean", 
               "ocean", 
               "ship1", 
               "ship1", 
               "ship1", 
               "ocean", 
               "ocean", 
              ],
              [ // E
               "ship1", 
               "ocean", 
               "ship1", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
              ],
              [ // F
               "ship1", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
              ],
              [ // G
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
              ],
              [ // H
               "ocean", 
               "ocean", 
               "ship1", 
               "ship1", 
               "ship1", 
               "ship1", 
               "ship1", 
               "ocean", 
               "ocean", 
               "ocean", 
              ],
              [ // I
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ship1", 
               "ocean", 
               "ocean", 
              ],
              [ // J
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ocean", 
               "ship1", 
               "ocean", 
               "ocean", 
              ]
             ];

export default function getTDFData(row: number, col: number) {
  return TDFDATA[row][col];
}
