global:
  opentdf:
    common:
      oidcExternalBaseUrl: https://platform.apps.openshift-opentdf.develop.virtru.com
      ingress:
        hostname: platform.apps.openshift-opentdf.develop.virtru.com
        gatewaySelector: ingressgateway

backend:
  keycloak:
    # https://fswb-documentation.knowis.net/1.0/Installation/content/install_3rd_party_os3.html
    podSecurityContext:
      fsGroup: 1000670000

    securityContext:
      runAsUser: 1000670000
      runAsNonRoot: true
