apiVersion: v1
kind: ConfigMap
metadata:
  name: zap-advanced-scan-config
data:
  scan-config.yaml: |-
    contexts:
      - name: scb-context
        url: http://opentdf-key-access:8000/
    apis:
      - name: scb-api
        context: scb-context
        format: openapi
        url: http://opentdf-key-access:8000/openapi.json
---
apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: "zap-scan"
  labels:
    organization: "OWASP"
spec:
  scanType: "zap-advanced-scan"
  parameters:
    - "-t"
    - "http://opentdf-key-access:8000/"
  volumeMounts:
    - name: zap-advanced-scan-config
      mountPath: /home/securecodebox/configs/scan-config.yaml
      subPath: scan-config.yaml
      readOnly: true
  volumes:
    - name: zap-advanced-scan-config
      configMap:
        name: zap-advanced-scan-config

