apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          env:
          - name: KAS_URL
            value: "http://kas:8000"
          - name: OIDC_ENDPOINT
            value: "http://keycloak-http"
          image: opentdf/example-web-app-image
          ports:
            - containerPort: 4070
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: web-app
spec:
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              service:
                name: web-app
                port:
                  number: 4070
            path: /web-app(/|$)(.*)
            pathType: Prefix
