apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          env:
          - name: KAS_URL
            value: "http://kas:8000"
          - name: OIDC_ENDPOINT
            value: "http://keycloak-http"
          image: opentdf/web-app
          ports:
            - containerPort: 4070
