# Tiltfile for development
# https://docs.tilt.dev/api.html
#

include('../../quickstart/Tiltfile')

# frontend
k8s_yaml("kubernetes.yaml")
k8s_resource(
    "web-app",
    resource_deps = ["keycloak-bootstrap"],
    labels="web-app",
    port_forwards = '4070:4070'
)

docker_build(
    "opentdf/web-app",
    ".",
    live_update = [
        sync(".", "/app"),
        run("cd /app && pip install -r requirements.txt", trigger = "./requirements.txt"),
    ],
)
