logLevel: DEBUG
serverPublicName: "OpenTDF Web App"
serverRootPath: /

image:
  pullPolicy: IfNotPresent
  name: opentdf/web-app

serviceAccount:
  # Specifies whether a service account should be created
  create: true

service:
  type: ClusterIP
  port: 4070

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  className: nginx
  hosts:
    localhost: &paths
      "/web-app(/|$)(.*)":
        pathType: Prefix
    host.docker.internal: *paths

# ingress:
#   enabled: true
#   className: nginx
#   hosts:
#     - host: localhost
#       paths:
#         - path: /web-app(/|$)(.*)
#           pathType: Prefix