image:
  # Keycloak is a non-OpenTDF chart, but with an OpenTDF image
  repository: ghcr.io/opentdf/keycloak
  tag: 0.0.0-sha-eb68a90
extraEnv: |
  - name: CLAIMS_URL
    value: http://opentdf-entitlement-pdp:3355/entitlements
  - name: JAVA_OPTS_APPEND
    value: -Dkeycloak.profile=preview -Dkeycloak.profile.feature.token_exchange=enabled
extraEnvFrom: |
  - secretRef:
      name: 'keycloak-secrets'
ingress:
  enabled: true
  ingressClassName: nginx
  rules:
    - host: localhost
      paths: &paths
        - path: /auth(/|$)(.*)
          pathType: Prefix
    - host: host.docker.internal
      paths: *paths
    - host: offline.demo.internal
      paths: *paths
    - host: opentdf.local
      paths: *paths
  tls: null
