image:
  repository: virtru/keycloak-h3-poc
  tag: 0.4.1

##  https://artifacthub.io/packages/helm/bitnami/keycloak
auth:
  createAdminUser: true
  adminUser: keycloakadmin
  adminPassword: mykeycloakpassword

extraEnvVars:
  - name: KEYCLOAK_LOG_LEVEL
    value: DEBUG
  - name: KEYCLOAK_USER
    value: keycloakadmin
  - name: KEYCLOAK_PASSWORD
    value: mykeycloakpassword
  - name: ATTRIBUTE_PROVIDER_URL
    value: http://opentdf-claims
  - name: KEYCLOAK_EXTRA_ARGS
    value: "-Dkeycloak.frontendUrl=https://localhost/keycloak/auth -Dkeycloak.adminUrl=https://localhost/keycloak/auth"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /keycloak
  hostname: localhost
