apiVersion: v1
kind: Secret
metadata:
  name: attributes-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.attributes.postgres.password }}

---

apiVersion: v1
kind: Secret
metadata:
  name: claims-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.claims.postgres.password }}
  EAS_PRIVATE_KEY: |-
        {{ .Files.Get "keystore/mock-claims-private-key.pem" | b64enc }}
  EAS_CERTIFICATE: |-
        {{ .Files.Get "keystore/mock-claims-certificate.pem" | b64enc }}
  KAS_EC_SECP256R1_CERTIFICATE: |-
        {{ .Files.Get "keystore/mock-key-access-ec-certificate.pem" | b64enc }}
  KAS_CERTIFICATE: |-
        {{ .Files.Get "keystore/mock-key-access-certificate.pem" | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: entitlement-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.entitlement.postgres.password }}

---

apiVersion: v1
kind: Secret
metadata:
  name: key-access-secrets
type: Opaque
data:
  EAS_CERTIFICATE: |-
        {{ .Files.Get "keystore/mock-claims-certificate.pem" | b64enc }}
  KAS_EC_SECP256R1_CERTIFICATE: |-
        {{ .Files.Get "keystore/mock-key-access-ec-certificate.pem" | b64enc }}
  KAS_CERTIFICATE: |-
        {{ .Files.Get "keystore/mock-key-access-certificate.pem" | b64enc }}
  KAS_EC_SECP256R1_PRIVATE_KEY: |-
        {{ .Files.Get "keystore/mock-key-access-ec-private-key.pem" | b64enc }}
  KAS_PRIVATE_KEY: |-
        {{ .Files.Get "keystore/mock-key-access-private-key.pem" | b64enc }}
