#!/usr/bin/env bash
#  Validate the current exported offline bundle
#    * Makes sure the last run of build-offline-bundle completed successfully
#    * Makes sure it is up to date (check for git HEAD digest match)
#    * TK Loads images into docker agent
#    * TK Helm installs into a kind cluster and runs KUTTL test

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
export PATH="$PATH:$APP_DIR/scripts"

monolog TRACE "Running [$0${1+ }$*]"

: "${EXPORT_ROOT:="$(git rev-parse --show-toplevel)/build/export/bundle"}"
: "${CONTAINERS_DIR:="${EXPORT_ROOT}/containers"}"
: "${LOCAL_TOOL:="kind"}"

export LOCAL_TOOL

suffix="$(<${EXPORT_ROOT}/BUNDLE_TAG)"
if [[ ! ${suffix} ]]; then
  monolog ERROR "Bundle is missing required label metadata"
  exit 1
fi


for first in abacus attributes claims entitlements kas keycloak-bootstrap keycloak; do
  prefix="${CONTAINERS_DIR}/opentdf-${first}-${suffix}"
  monolog TRACE "docker load image from [${prefix}.tar]"
  if ! docker load -i "${prefix}.tar" ; then
    monolog ERROR "offline bundle for [${first}] failed to load"
    exit 1
  fi
  meta=$(<"${prefix}.meta")
  abstag=${meta%% *}
  reponame=${meta%%[:@ ]*}
  prettytag=${meta##*:}
  if ! docker tag "$reponame:$prettytag" "$reponame:offline"; then
    monolog ERROR "1st party bundle [${first}] failed to [docker tag $reponame:$prettytag $reponame:offline]"
    exit 1
  fi
done

for third in kind postgresql; do
  prefix="${CONTAINERS_DIR}/third-party-image-${third}-${suffix}"
  monolog TRACE "docker load kind from [${prefix}.tar]"
  if ! docker load -i "${prefix}.tar" ; then
    monolog ERROR "offline bundle for [${third}] failed to load"
    exit 1
  fi
  meta=$(<"${prefix}.meta")
  abstag=${meta%% *}
  reponame=${meta%%[:@ ]*}
  # Tag image with tag we are matching in the pull
  # meta has two values so we want it to split into two parameters
  # shellcheck disable=SC2086
  if ! docker tag "$abstag" "$reponame"; then
    monolog ERROR "3rd party bundle [${third}] failed: [docker tag ${meta}]"
    exit 1
  fi

  # Tag image with `offline`. The percent below strips everything
  # after (and including) the first colon
  if ! docker tag "$abstag" "$reponame:offline"; then
    monolog ERROR "3rd party bundle [${third}] failed to [docker tag $abstag $reponame:offline]"
    exit 1
  fi
done
