apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: platform-gateway
spec:
  selector:
    istio: {{ .Values.global.opentdf.common.ingress.gatewaySelector }}
  servers:
    - hosts:
        - {{ .Values.global.opentdf.common.ingress.hostname }}
      port:
        name: https
        number: 443
        {{- if .Values.global.opentdf.common.tls }}
        protocol: HTTPS
        tls:
          mode: SIMPLE
          credentialName: opentdf-tls
        {{- else }}
        protocol: HTTP
        {{- end }}
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.global.opentdf.common.ingress.hostname }}
      tls:
        httpsRedirect: {{ .Values.global.opentdf.common.ingress.httpsRedirect }}
