attributes:
  serverUrl: http://localhost:65432/api/attributes
entitlements:
  serverUrl: http://localhost:65432/api/entitlements
oidc:
  serverUrl: http://localhost:65432/auth/
  clientId: tdf-entitlements
  realm: tdf
ingress:
  enabled: true
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
  annotations:
    kubernetes.io/ingress.class: nginx
