attributes:
  serverUrl: http://attributes:4020
entitlements:
  serverUrl: http://entitlements:4030
oidc:
  serverUrl: http://localhost:65432/auth/
  clientId: tdf-entitlement
  realm: tdf
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
