attributes:
  serverUrl: http://localhost:65432/api/attributes
basePath: ""
entitlements:
  serverUrl: http://localhost:65432/api/entitlements
oidc:
  serverUrl: http://localhost:65432/auth/
  clientId: tdf-entitlement
  queryRealms: tdf
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
