image:
  image: ghcr.io/opentdf/claims:main
imagePullSecrets:
  - name: ghcr-registry-key
secretRef:
 name: claims-secrets
service:
  port: 5000
postgres:
  host: postgresql
  port: 5432
  user: tdf_entitlement_reader
  password: bXlQb3N0Z3Jlc1Bhc3N3b3Jk
  database: tdf_database
  schema: tdf_entitlement
