# Tiltfile for development
# https://docs.tilt.dev/api.html
#

include('../../quickstart/Tiltfile')

#k8s_resource("kas", resource_deps=["opentdf-attributes"], port_forwards="8000:8000")

# sample web app
k8s_yaml("kubernetes.yaml")
k8s_resource(
    "opentdf-abacship",
    resource_deps = ["keycloak-bootstrap"],
    labels="frontend",
)

docker_build(
    "opentdf/abacship",
    "."
)
