# Tiltfile for development
# https://docs.tilt.dev/api.html
#

include("../../quickstart/Tiltfile")

k8s_yaml("kubernetes.yaml")

docker_build(
    "ghcr.io/opentdf/nanotdf-client-app",
    ".",
    live_update=[
        # when package.json changes, we need to do a full build
        fall_back_on(["package.json", "package-lock.json"]),
        # Map the local source code into the container under /src
        sync(".", "/src"),
    ],
)

k8s_resource(
    "nanotdf-client-app",
    labels="frontend",
    links=link("http://localhost:65432/nanotdf-client-app"),
    resource_deps=["keycloak", "kas"],
)
