name: 'Update aggregate openapi'
on:
  workflow_dispatch:
    inputs:
      version:
        description: "The backend tag/branch you want to reference"
        required: true

jobs:
  update-aggregate-openapi:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: opentdf

      - name: Checkout backend repo
        uses: actions/checkout@v4
        with:
          repository: opentdf/backend
          path: backend
          ref: ${{ inputs.version }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: create a new branch
        working-directory: opentdf
        run: |-
          git checkout -b job-update-aggregate-openapi-${{ inputs.version }}-${{ github.run_id }}
          git push origin job-update-aggregate-openapi-${{ inputs.version }}-${{ github.run_id }}

      - name: update the openapi
        run: |-
          cd opentdf/openapi
          npm i
          npx openapi-merge-cli
          jq '.output = "./openapi-aggregate.json"' openapi-merge.json >openapi-merge2.json
          npx openapi-merge-cli --config openapi-merge2.json
          rm openapi-merge2.json

      - name: commit the yaml changes
        working-directory: opentdf
        env:
          GITHUB_TOKEN: ${{ github.token }}
          FILE_TO_COMMIT: openapi/openapi-aggregate.yaml
          DESTINATION_BRANCH: job-update-aggregate-openapi-${{ inputs.version }}-${{ github.run_id }}
        run: |
          export MESSAGE="Updating aggregate openapi yaml"
          export SHA=$( git rev-parse $DESTINATION_BRANCH:$FILE_TO_COMMIT )
          export CONTENT=$( base64 -i $FILE_TO_COMMIT )
          gh api --method PUT /repos/opentdf/opentdf/contents/$FILE_TO_COMMIT \
            --field message="$MESSAGE" \
            --field content="$CONTENT" \
            --field encoding="base64" \
            --field branch="$DESTINATION_BRANCH" \
            --field sha="$SHA"

      - name: commit the json changes
        working-directory: opentdf
        env:
          GITHUB_TOKEN: ${{ github.token }}
          FILE_TO_COMMIT: openapi/openapi-aggregate.json
          DESTINATION_BRANCH: job-update-aggregate-openapi-${{ inputs.version }}-${{ github.run_id }}
        run: |
          export MESSAGE="Updating aggregate openapi json"
          export SHA=$( git rev-parse $DESTINATION_BRANCH:$FILE_TO_COMMIT )
          export CONTENT=$( base64 -i $FILE_TO_COMMIT )
          gh api --method PUT /repos/opentdf/opentdf/contents/$FILE_TO_COMMIT \
            --field message="$MESSAGE" \
            --field content="$CONTENT" \
            --field encoding="base64" \
            --field branch="$DESTINATION_BRANCH" \
            --field sha="$SHA"

      - name: create a PR
        working-directory: opentdf
        run: |-
          gh pr create -B main -H job-update-aggregate-openapi-${{ inputs.version }}-${{ github.run_id }} --title 'Update aggregate openapi with backend version ${{ inputs.version }}' --body 'Created by "Update aggregate openapi" github action with opentdf github-actions bot'
        env:
          GH_TOKEN: ${{ github.token }}
