name: 'Update aggregate openapi'
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the backend tag you want to reference"
        required: true

jobs:
  update-aggregate-openapi:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: opentdf

      - name: Checkout backend repo
        uses: actions/checkout@v4
        with:
          repository: opentdf/backend
          path: backend
          ref: 1.5.0 #${{ inputs.version }}
      
      - name: create a new branch
        run: |-
          cd opentdf
          git status