name: Create Release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release Version'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Input release version
        run: printf 'Input release version ${{ github.event.inputs.releaseVersion }}'
