on:
  push:
    branches:
      - feature/PLAT-2146
jobs:
  dispatch_if_charts_updated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: charts_versions.json
      - run: |-
        (
          if [ -f "charts_versions1.json" ]; then
            echo "file exists."
          else
            echo "no file"
          fi
        )
