on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  dispatch_if_charts_updated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: charts_versions.json
      - run: |-
        if [test -f "version.txt"] 
        then
          echo "no file"
        else
          echo "file exists."
        fi
