on:
  push:
    branches:
      - 'feature/PLAT-2046'
  # schedule: 
  #   # runs once a week on sunday
  #   - cron: "55 23 * * 0"
      # for testing
    
jobs:
  # This workflow contains a single job called "traffic"
  traffic:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: View context attributes
      uses: actions/github-script@v6
      with:
        script: console.log(context)
    - name: GitHub traffic  
      uses: actions/github-script@v6
      id: get-traffic
      with:
        github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} 
        retries: 3
        script: |
          const views = github.rest.repos.getViews({
          owner: context.repo.owner,
          repo: context.repo.repo,
          })
          const clones = github.repos.getClones({
          owner: context.repo.owner,
          repo: context.repo.repo,
          })
          return {views: views, clones: clones}
    - name: Get result
      run: echo "${{steps.get-traffic.outputs.result}}"