on:
  push:
    branches:
      - 'feature/PLAT-2046'
  # schedule: 
  #   # runs once a week on sunday
  #   - cron: "55 23 * * 0"
      # for testing
    
jobs:
  # This workflow contains a single job called "traffic"
  traffic:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: GitHub traffic  
      uses: actions/github-script@v6
      env:
          TRAFFIC_ACTION_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} 
      id: get-traffic
      with:
        retries: 3
        script: |
        console.log(context)
        console.log(${{ github.rest }})
        return github.rest.traffic.get({
        owner: context.repo.owner,
        repo: context.repo.repo,
        })
    - name: Get result
      run: echo "${{steps.get-traffic.outputs.result}}"