on:
  push:
    branches:
      - 'feature/PLAT-2046'
  # schedule: 
  #   # runs once a week on sunday
  #   - cron: "55 23 * * 0"
      # for testing
    
jobs:
  # This workflow contains a single job called "traffic"
  traffic:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: write-all
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: View context attributes
      uses: actions/github-script@v6
      with:
        script: console.log(context)
    - name: checkout repo
      uses: actions/checkout@v3
    - name: GitHub traffic  
      uses: actions/github-script@v6
      id: get-traffic
      with:
        github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} 
        retries: 3
        script: |
          const script = require('./scripts/metrics.js')
          const result = await script({github, context})
          console.log(result)
          return result
    - name: Write to CSV
      uses: gr2m/write-csv-file-action@v1.x
      with:
        path: data/traffic.csv
        columns: timestamp, views, clones, forks
          timestamp: ${{ fromJson(steps.get-traffic.outputs.result).timestamp }}
          views: ${{ fromJson(steps.get-traffic.outputs.result).views }}
          clones: ${{ fromJson(steps.get-traffic.outputs.result).clones }}
          forks: ${{ fromJson(steps.get-traffic.outputs.result).forks }}
    - name: Commit CSV 
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data
        git commit -m "OpenTDF-Bot; data/traffic.csv updated"
        "git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

   # - name: Push to Amplitude
   #   run: >-
   #     echo "${{steps.get-traffic.outputs.result}}"
   #     curl --data '{"api_key": "xx", "events": [${{steps.get-traffic.outputs.result}}]}' https://api.amplitude.com/2/httpapi